### ISSUE TITLE
[FEATURE] More information error messages for create

### ISSUE THREAD

**Issue by samlaf** [dynamoose/dynamoose#1254]
When [creating](https://dynamoosejs.com/guide/Model#modelcreatedocument-settings-callback) a document whose primarykey already exists in the database, dynamoose results in the following error
```
(node:74493) UnhandledPromiseRejectionWarning: ConditionalCheckFailedException: The conditional request failed
    at Request.extractError (/home/samlaf/dev/oa-media-cdk-stacks/node_modules/dynamoose/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/home/samlaf/dev/oa-media-cdk-stacks/node_modules/dynamoose/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/samlaf/dev/oa-media-cdk-stacks/node_modules/dynamoose/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/samlaf/dev/oa-media-cdk-stacks/node_modules/dynamoose/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/samlaf/dev/oa-media-cdk-stacks/node_modules/dynamoose/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/samlaf/dev/oa-media-cdk-stacks/node_modules/dynamoose/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/samlaf/dev/oa-media-cdk-stacks/node_modules/dynamoose/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/samlaf/dev/oa-media-cdk-stacks/node_modules/dynamoose/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/samlaf/dev/oa-media-cdk-stacks/node_modules/dynamoose/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/home/samlaf/dev/oa-media-cdk-stacks/node_modules/dynamoose/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:74493) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:74493) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
It would be nice to have an error message more information than `ConditionalCheckFailedException`, since when looking through multiple concurrent logs in aws logwatch, its really not obvious which ConditionalCheck failed.

**Comment by fishcharlie** [comment]
@samlaf This is a balancing act here. This error comes from the AWS-SDK. So on some level, any additional details **should** come from them. On the other hand, I understand Dynamoose being able to do more to assist in cases like this. Part of this gets into the concept of plugins (which Dynamoose v1 supported in beta, and v2 removed completely). Considering bringing back plugins in v3, but not sure if it'll happen.

For the time being tho, I don't see this being integrated into Dynamoose itself anytime in the foreseeable future.

The best advice I can give for now, is to add your own error handling (which you probably should be doing regardless). Errors do occur, and leaving it up to a `UnhandledPromiseRejectionWarning`, I don't think is the best practice at all. If you were to handle the errors appropriately, this would give you a clear path to be able to log additional information about where and what is causing the error.
