### ISSUE TITLE
Possible to get the x-amzn-requestid from DynamoDB response ?

### ISSUE THREAD

**Issue by fishcharlie** [dynamoose/dynamoose#1395]
### Discussed in https://github.com/dynamoose/dynamoose/discussions/1394

<div type='discussions-op-text'>

<sup>Originally posted by **chamorin** May  5, 2022</sup>
I was wondering if I can have the `x-amzn-requestid` from a request response. In my case I'm doing a `Model.get(id)` and I want to add the AWS request id in my error body response. So if the request does not found the resource, my API would return a 404 with the AWS request id from the request that did the `get()`.</div>

**Comment by Drarig29** [comment]
```
ProvisionedThroughputExceededException: The level of configured provisioned throughput for the table was exceeded. Consider increasing your provisioning level with the UpdateTable API.
    at deserializeAws_json1_0UpdateItemCommandError (/home/.../node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:4014:41)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at /home/.../node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at /home/.../node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at StandardRetryStrategy.retry (/home/.../node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at /home/.../node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at main (/home/.../node_modules/dynamoose/dist/aws/ddb/internal.js:6:20)
    at /home/.../node_modules/dynamoose/dist/Model/index.js:618:34
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '5B7KD9HEIR7JQMG465MCIDL1PVVV4KQNSO5AEMVJF66Q9ASUAAJG',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 3,
    totalRetryDelay: 1531
  },
  '$response': HttpResponse {
    statusCode: 400,
    headers: {
      server: 'Server',
      date: 'Thu, 05 May 2022 19:58:38 GMT',
      'content-type': 'application/x-amz-json-1.0',
      'content-length': '241',
      connection: 'keep-alive',
      'x-amzn-requestid': '5B7KD9HEIR7JQMG465MCIDL1PVVV4KQNSO5AEMVJF66Q9ASUAAJG',
      'x-amz-crc32': '1545824508'
    },
```

Just do a try-catch, and you should find what you want in `err.$response.headers["x-amzn-requestid"]`.

**Comment by fishcharlie** [comment]
Closing since @Drarig29 provided an answer here.
